### ISSUE TITLE
使用flutter_orm_plugin  打包安装失败

### ISSUE THREAD

**Issue by liu616517071** [williamwen1986/flutter_orm_plugin#4]
使用flutter_orm_plugin  打包apk安装失败，错误信息如下：
![image](https://user-images.githubusercontent.com/18673416/103763386-b3dcd080-5054-11eb-9173-8f283f9a38ca.png)
这是什么原因呢？

**Comment by liu616517071** [comment]
Error -4 during AudioRecord native read
: [01-06/19:07:56.323:F:jni_android.cc(116)] Check failed: !ClearException(env) && clazz. Failed to find class org/chromium/base/ActivityStatus
 JNI DETECTED ERROR IN APPLICATION: java_class == null
     in call to RegisterNatives
     from java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String)
 "main" prio=5 tid=1 Runnable
   | group="main" sCount=0 dsCount=0 obj=0x74b042a0 self=0xf5236500
   | sysTid=14732 nice=0 cgrp=default sched=0/0 handle=0xf73cab34
   | state=R schedstat=( 84229584 7360465 78 ) utm=3 stm=4 core=4 HZ=100
   | stack=0xff79c000-0xff79e000 stackSize=8MB
   | held mutexes= "mutator lock"(shared held)
   native: #00 pc 0035a55f  /system/lib/libart.so (_ZN3art15DumpNativeStackERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEEiPKcPNS_9ArtMethodEPv+126)
   native: #01 pc 0033b0e7  /system/lib/libart.so (_ZNK3art6Thread4DumpERNSt3__113basic_ostreamIcNS1_11char_traitsIcEEEE+138)
   native: #02 pc 0024dfcb  /system/lib/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+750)
   native: #03 pc 0024e6d3  /system/lib/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+62)
   native: #04 pc 002817bf  /system/lib/libart.so (_ZN3art3JNI21RegisterNativeMethodsEP7_JNIEnvP7_jclassPK15JNINativeMethodib+3722)
   native: #05 pc 002819d5  /system/lib/libart.so (_ZN3art3JNI15RegisterNativesEP7_JNIEnvP7_jclassPK15JNINativeMethodi+8)
   native: #06 pc 00142c97  /data/app/com.romantic.novel.hot.flutter_funny_novel-1/lib/arm/libluaFramework.so (???)
   native: #07 pc 00117c8b  /data/app/com.romantic.novel.hot.flutter_funny_novel-1/lib/arm/libluaFramework.so (???)
   native: #08 pc 00114fc9  /data/app/com.romantic.novel.hot.flutter_funny_novel-1/lib/arm/libluaFramework.so (???)
   native: #09 pc 0007cafd  /data/app/com.romantic.novel.hot.flutter_funny_novel-1/lib/arm/libluaFramework.so (JNI_OnLoad+92)
   native: #10 pc 0024eba7  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectPS9_+1190)
   native: #11 pc 002c02eb  /system/lib/libart.so (_ZN3artL18Runtime_nativeLoadEP7_JNIEnvP7_jclassP8_jstringP8_jobjectS5_+178)
   native: #12 pc 00212105  /data/dalvik-cache/arm/system@framework@boot.oat (Java_java_lang_Runtime_nativeLoad__Ljava_lang_String_2Ljava_lang_ClassLoader_2Ljava_lang_String_2+144)
   at java.lang.Runtime.nativeLoad(Native method)
   at java.lang.Runtime.doLoad(Runtime.java:435)
   - locked <0x08506ae2> (a java.lang.Runtime)
   at java.lang.Runtime.loadLibrary(Runtime.java:370)
   at java.lang.System.loadLibrary(System.java:1076)
   at com.common.luakit.LuaHelper.<clinit>(:-1)
   at b.b.a.a.a(:-1)
   at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(:-1)
   at java.lang.reflect.Method.invoke!(Native method)
   at io.flutter.embedding.engine.a.q(:-1)
   at io.flutter.embedding.engine.a.<init>(:-1)
